<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

  <xacro:include filename="inertial_macros.xacro"/>

  <!-- Properties -->
  <xacro:property name="chassis_length" value="2.0"/>
  <xacro:property name="chassis_width" value="1.0"/>
  <xacro:property name="chassis_height" value="0.2"/>
  <xacro:property name="chassis_mass" value="10.0"/>

  <xacro:property name="wheel_radius" value="0.3"/>
  <xacro:property name="wheel_thickness" value="0.2"/>
  <xacro:property name="wheel_mass" value="2.0"/>

  <xacro:property name="wheel_offset_y" value="0.55"/>
  <xacro:property name="wheel_offset_z" value="0.0"/>

  <xacro:property name="caster_wheel_radius" value="0.05"/>
  <xacro:property name="caster_wheel_mass" value="0.5"/>
  <xacro:property name="caster_wheel_offset_x" value="0.15"/>
  <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>

  <!-- Materials -->
  <material name="white"><color rgba="1 1 1 1"/></material>
  <material name="orange"><color rgba="1 0.3 0.1 1"/></material>
  <material name="blue"><color rgba="0.2 0.2 1 1"/></material>
  <material name="black"><color rgba="0 0 0 1"/></material>
  <material name="red"><color rgba="1 0 0 1"/></material>

  <!-- Base & Chassis -->
  <link name="base_link"/>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>
  <link name="base_footprint"/>

  <joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
    <origin xyz="-0.95 0 0.0"/>
  </joint>

  <link name="chassis">
    <visual>
      <origin xyz="1.0 0 ${chassis_height/2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="1.0 0 ${chassis_height/2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>
  <gazebo reference="chassis">
    <material>Gazebo/Orange</material>
  </gazebo>

  <!-- Wheels -->
  <!-- Drive Wheels (Front Most) -->
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="-0.6 ${wheel_offset_y} ${wheel_offset_z}" rpy="0 1.5708 0"/>
    <axis xyz="0 1 0"/>
  </joint>
  <link name="left_wheel">
    <visual>
      <origin rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>
  <gazebo reference="left_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="-0.6 -${wheel_offset_y} ${wheel_offset_z}" rpy="0 1.5708 0"/>
    <axis xyz="0 1 0"/>
  </joint>
  <link name="right_wheel">
    <visual>
      <origin rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>
  <gazebo reference="right_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- Free Wheels (3 each side) -->
  <xacro:macro name="freewheel" params="name x y">
    <joint name="${name}_joint" type="revolute">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} ${wheel_offset_z}" rpy="0 1.5708 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-3.1415" upper="3.1415" effort="0.1" velocity="1.0"/>
    </joint>
    <link name="${name}">
      <visual>
        <origin rpy="1.5708 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin rpy="1.5708 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
    </link>
  </xacro:macro>

  <!-- Left side -->
  <xacro:freewheel name="freewheel_left_1" x="0.0" y="${wheel_offset_y}"/>
  <xacro:freewheel name="freewheel_left_2" x="0.6" y="${wheel_offset_y}"/>
  <xacro:freewheel name="freewheel_left_3" x="1.2" y="${wheel_offset_y}"/>

  <!-- Right side -->
  <xacro:freewheel name="freewheel_right_1" x="0.0" y="-${wheel_offset_y}"/>
  <xacro:freewheel name="freewheel_right_2" x="0.6" y="-${wheel_offset_y}"/>
  <xacro:freewheel name="freewheel_right_3" x="1.2" y="-${wheel_offset_y}"/>

  <!-- Caster Wheel -->
  <joint name="caster_wheel_joint" type="fixed">
    <parent link="chassis"/>
    <child link="caster_wheel"/>
    <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
  </joint>
  <link name="caster_wheel">
    <visual>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_sphere>
  </link>
  <gazebo reference="caster_wheel">
    <material>Gazebo/White</material>
    <mu1 value="0.001"/>
    <mu2 value="0.001"/>
  </gazebo>

</robot>
